function result = Simulate(OB_GUI_parameters, opts)
%SIMULATE Run charging + discharging with optional streaming handler.

if nargin < 2 || isempty(opts)
    opts = struct();
end

[T_empty_charging, E_elec_in_kWh, H_loss_total_charging, ...
    H_loss_major_charging, H_loss_minor_charging, H_loss_major_umbilical_charging, ...
    H_loss_minor_umbilical_charging, H_static_charging, H_pump, Q_pump, ...
    V_wat_rigid_charging, E_elec_in_J, i_charging] = Charging(OB_GUI_parameters, opts);

[H_loss_total_discharging, H_loss_minor_discharging, H_loss_major_discharging, ...
    H_loss_major_umbilical_discharging, H_loss_minor_umbilical_discharging, ...
    H_static_discharging, H_turbine, Q_turbine, V_wat_rigid_discharging, ...
    V_wat_bladder, P_generator, N_roundtrip, T_empty_discharging, ...
    E_elec_out_kWh, i_discharging] = Discharging(OB_GUI_parameters, V_wat_rigid_charging, E_elec_in_J, opts);

result = struct( ...
    'charging', struct( ...
        'T_empty_charging', T_empty_charging, ...
        'E_elec_in_kWh', E_elec_in_kWh, ...
        'H_loss_total', H_loss_total_charging, ...
        'H_loss_major', H_loss_major_charging, ...
        'H_loss_minor', H_loss_minor_charging, ...
        'H_loss_major_umbilical', H_loss_major_umbilical_charging, ...
        'H_loss_minor_umbilical', H_loss_minor_umbilical_charging, ...
        'H_static', H_static_charging, ...
        'H_pump', H_pump, ...
        'Q', Q_pump, ...
        'V_rigid', V_wat_rigid_charging, ...
        'E_elec_in_J', E_elec_in_J, ...
        'i', i_charging), ...
    'discharging', struct( ...
        'H_loss_total', H_loss_total_discharging, ...
        'H_loss_minor', H_loss_minor_discharging, ...
        'H_loss_major', H_loss_major_discharging, ...
        'H_loss_major_umbilical', H_loss_major_umbilical_discharging, ...
        'H_loss_minor_umbilical', H_loss_minor_umbilical_discharging, ...
        'H_static', H_static_discharging, ...
        'H_turbine', H_turbine, ...
        'Q', Q_turbine, ...
        'V_rigid', V_wat_rigid_discharging, ...
        'V_bladder', V_wat_bladder, ...
        'P_generator', P_generator, ...
        'N_roundtrip', N_roundtrip, ...
        'T_empty_discharging', T_empty_discharging, ...
        'E_elec_out_kWh', E_elec_out_kWh, ...
        'i', i_discharging));
end
